{
  "comments": [
    {
      "key": {
        "uuid": "9da5cf98_dec4604a",
        "filename": "tcp_tests/tests/system/test_failover_ceph.py",
        "patchSetId": 4
      },
      "lineNbr": 151,
      "author": {
        "id": 1016956
      },
      "writtenOn": "2019-08-27T08:14:28Z",
      "side": 1,
      "message": "Let\u0027s add assert \"Node {} didn\u0027t come back after reboot\"",
      "range": {
        "startLine": 151,
        "startChar": 8,
        "endLine": 151,
        "endChar": 68
      },
      "revId": "13f8f85407aa1ae0ff8055b53899a073956e0004",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d8aafeec_a7b22d9f",
        "filename": "tcp_tests/tests/system/test_failover_ceph.py",
        "patchSetId": 4
      },
      "lineNbr": 151,
      "author": {
        "id": 1016850
      },
      "writtenOn": "2019-08-27T13:49:19Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "9da5cf98_dec4604a",
      "range": {
        "startLine": 151,
        "startChar": 8,
        "endLine": 151,
        "endChar": 68
      },
      "revId": "13f8f85407aa1ae0ff8055b53899a073956e0004",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9dae2f3f_c217f96a",
        "filename": "tcp_tests/tests/system/test_failover_ceph.py",
        "patchSetId": 4
      },
      "lineNbr": 256,
      "author": {
        "id": 1016956
      },
      "writtenOn": "2019-08-27T08:14:28Z",
      "side": 1,
      "message": "Let\u0027s add assert \"Node {} didn\u0027t come back after reboot\"",
      "range": {
        "startLine": 256,
        "startChar": 8,
        "endLine": 256,
        "endChar": 68
      },
      "revId": "13f8f85407aa1ae0ff8055b53899a073956e0004",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "f61a6452_30032317",
        "filename": "tcp_tests/tests/system/test_failover_ceph.py",
        "patchSetId": 4
      },
      "lineNbr": 256,
      "author": {
        "id": 1016850
      },
      "writtenOn": "2019-08-27T13:49:19Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "9dae2f3f_c217f96a",
      "range": {
        "startLine": 256,
        "startChar": 8,
        "endLine": 256,
        "endChar": 68
      },
      "revId": "13f8f85407aa1ae0ff8055b53899a073956e0004",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "f2a61f0a_80d47d8c",
        "filename": "tcp_tests/tests/system/test_failover_ceph.py",
        "patchSetId": 4
      },
      "lineNbr": 360,
      "author": {
        "id": 1016956
      },
      "writtenOn": "2019-08-27T08:14:28Z",
      "side": 1,
      "message": "Let\u0027s add assert \"Node {} didn\u0027t come back after reboot\"",
      "range": {
        "startLine": 360,
        "startChar": 8,
        "endLine": 360,
        "endChar": 68
      },
      "revId": "13f8f85407aa1ae0ff8055b53899a073956e0004",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "eae71ccb_f85b8227",
        "filename": "tcp_tests/tests/system/test_failover_ceph.py",
        "patchSetId": 4
      },
      "lineNbr": 360,
      "author": {
        "id": 1016850
      },
      "writtenOn": "2019-08-27T13:49:19Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "f2a61f0a_80d47d8c",
      "range": {
        "startLine": 360,
        "startChar": 8,
        "endLine": 360,
        "endChar": 68
      },
      "revId": "13f8f85407aa1ae0ff8055b53899a073956e0004",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}